# Generated by Django 3.2.8 on 2021-10-29 23:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('matrix_user_id', models.CharField(max_length=200)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('cached_displayname', models.CharField(blank=True, max_length=200, null=True)),
                ('cached_is_guest', models.BooleanField(default=False)),
                ('cached_deactivated', models.BooleanField(default=False)),
                ('cached_shadow_banned', models.BooleanField(default=False)),
                ('cached_consent_version', models.CharField(blank=True, max_length=200, null=True)),
                ('cached_appservice_id', models.CharField(blank=True, max_length=200, null=True)),
                ('cached_creation_ts', models.CharField(max_length=200)),
                ('cached_user_type', models.CharField(blank=True, max_length=200, null=True)),
                ('cached_avatar_url', models.CharField(blank=True, max_length=400, null=True)),
                ('cached_json', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Adminaccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('access_token', models.CharField(max_length=200)),
                ('homeserver', models.CharField(max_length=200)),
                ('port', models.IntegerField(default=443)),
                ('device_id', models.CharField(max_length=200)),
                ('server_protocol', models.CharField(default='https://', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('adminaccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webadmin.adminaccount')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matrix_room_id', models.CharField(max_length=200)),
                ('comment', models.CharField(max_length=200)),
                ('cached_name', models.CharField(max_length=200)),
                ('managed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webadmin.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(blank=True, max_length=200, null=True)),
                ('current_tenancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current', to='webadmin.tenant')),
                ('matrix_user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webadmin.account')),
                ('tenancies', models.ManyToManyField(to='webadmin.Tenant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='managed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webadmin.tenant'),
        ),
    ]
